{
  "services": [
    {
      "type": "web",
      "name": "egypt-career-map",
      "env": "python",
      "region": "frankfurt",
      "plan": "free",
      "buildCommand": "pip install -r requirements.txt",
      "startCommand": "gunicorn index:server",
      "envVars": [
        {
          "key": "PYTHON_VERSION",
          "value": "3.11.0"
        }
      ]
    }
  ]
}
