services:
  - type: web
    name: egypt-career-map-app
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn index:server
    branch: main
